# Site settings
# title: 2015M217
# email: colliand@math.ubc.ca
# description: # this means to ignore newlines until "baseurl:"
# baseurl: "/2015M217" # the subpath of your site, e.g. /blog/
# # url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: colliand
# # github_username:  colliand

name: James Colliander
title: James Colliander
# description: "Math, Research, Education"
# url: http://colliand.com
twitter_username: colliand
github_username: colliand



# Build settings
markdown: kramdown
timezone: America/Vancouver
highlighter: null
exclude: ["Gemfile", "Gemfile.lock"]
permalink: /:year/:month/:day/:title/


#disqus widget
disqus:
  shortname: 'colliand'
  count: 5

# jekyll-scholar
scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: <abbr>[{{key}}] </abbr>{{reference}}
  # bibliography_template: "%{reference}"
  replace_strings: true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"
  bibtex_filters:
     - markdown